trigger:
  branches:
    include: ["master", "*"]

queue:
  name: Hosted VS2017
  timeoutInMinutes: 10

steps:
- task: NodeTool@0
  displayName: Installing Node.js
  inputs:
    versionSpec: '8.x'

- script: npm install
  displayName: Restore packages

- script: npm run-script build
  displayName: Build

- task: ArchiveFiles@2
  displayName: Create vsls-guestbook archive
  inputs:
    rootFolderOrFile: $(System.DefaultWorkingDirectory)
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: Publish vsls-guestbook as artifact
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: vsls-guestbook
